EmpresaController.show_empresa_actual
puts "\n"
puts "\t\t**************************************************************************************************************************"
puts "\t\t**************************************************************************************************************************"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                    M  E  N  U 	P  R  I  N  C  I  P  A  L                                       **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                              (S) E L E C C I O N A R   E M P R E S A                                                 **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                              (E) M P R E S A S                                                                       **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                              (C) O N C E P T O S                                                                     **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                               L (O) C A L I D A D E S                                                                **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                               E (M) P L E A D O S                                                                    **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                               L (I) Q U I D A C I O N E S                                                            **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**                                                                                    F I N A L I Z A R  (Backspace)    **"
puts "\t\t**                                                                                                                      **"
puts "\t\t**************************************************************************************************************************"
puts "\t\t**************************************************************************************************************************"
puts ""
printf "\t\tSeleccione letra: "
