/****************** GENERATORS ********************/

CREATE GENERATOR CONCEPTOS_SEQ;
CREATE GENERATOR EMPLEADOS_SEQ;
CREATE GENERATOR EMPRESAS_SEQ;
CREATE GENERATOR LOCALIDADES_SEQ;

/******************** TABLES **********************/

CREATE TABLE CONCEPTOS
(
  ID integer NOT NULL,
  CODIGO integer,
  DESCRIPCION varchar(30),
  CONSTRAINT PK_CONCEPTOS PRIMARY KEY (ID),
  CONSTRAINT UNQ_CONCEPTOS_CODIGO UNIQUE (CODIGO)
);
CREATE TABLE CONCEPTOS_PERSONALES
(
  EMPLEADO_ID integer NOT NULL,
  CONCEPTO_ID integer NOT NULL,
  CONSTRAINT PK_CONCEPTOS_PERSONALES PRIMARY KEY (EMPLEADO_ID,CONCEPTO_ID)
);
CREATE TABLE EMPLEADOS
(
  ID integer NOT NULL,
  NRO_LEGAJO integer NOT NULL,
  NOMBRE_Y_APELLIDO varchar(30),
  FECHA_NACIMIENTO date,
  DNI varchar(10),
  LOCALIDAD_ID integer,
  EMPRESA_ID integer NOT NULL,
  CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID),
  CONSTRAINT UNQ_EMLPEADOS_EMPRESA UNIQUE (EMPRESA_ID,NRO_LEGAJO)
);
CREATE TABLE EMPRESAS
(
  ID integer NOT NULL,
  RAZON_SOCIAL varchar(30) NOT NULL,
  CUIT varchar(13),
  DOMICILIO varchar(35),
  LOCALIDAD_ID integer,
  CONSTRAINT PK_EMPRESAS PRIMARY KEY (ID),
  CONSTRAINT UNQ_EMPRESAS_CUIT UNIQUE (CUIT)
);
CREATE TABLE LOCALIDADES
(
  ID integer NOT NULL,
  NOMBRE varchar(25),
  CONSTRAINT PK_LOCALIDADES PRIMARY KEY (ID)
);

/******************** FOREIGN KEYS ********************/

ALTER TABLE EMPRESAS ADD CONSTRAINT FK_EMPR_LOC FOREIGN KEY (LOCALIDAD_ID) REFERENCES LOCALIDADES (ID);

ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPL_LOC FOREIGN KEY (LOCALIDAD_ID) REFERENCES LOCALIDADES (ID);
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPL_EMPR FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);

ALTER TABLE CONCEPTOS_PERSONALES ADD CONSTRAINT FK_CON_PER_EMPL FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS (ID);
ALTER TABLE CONCEPTOS_PERSONALES ADD CONSTRAINT FK_CON_PER_CON FOREIGN KEY (CONCEPTO_ID) REFERENCES CONCEPTOS (ID);
